//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela_Entity_basics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificación
    {
        public int IdCalificación { get; set; }
        public decimal Calificación1 { get; set; }
        public int IdMateria { get; set; }
        public int IdAlumno { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
